[build]
  base = "spotify-collage"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/api/proxy-image"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Pragma = "no-cache"
